# Generated by Django 5.2.6 on 2025-09-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('no_dr', 'No Diabetic Retinopathy'), ('mild', 'Mild Diabetic Retinopathy'), ('moderate', 'Moderate Diabetic Retinopathy'), ('severe', 'Severe Diabetic Retinopathy'), ('proliferative', 'Proliferative Diabetic Retinopathy')], max_length=50)),
                ('recommendation_text', models.TextField()),
                ('foods_to_eat', models.TextField(help_text='List of recommended foods, separated by commas')),
                ('foods_to_avoid', models.TextField(help_text='List of foods to avoid, separated by commas')),
            ],
        ),
        migrations.CreateModel(
            name='RetinopathyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='retinopathy_images/')),
                ('result', models.CharField(choices=[('no_dr', 'No Diabetic Retinopathy'), ('mild', 'Mild Diabetic Retinopathy'), ('moderate', 'Moderate Diabetic Retinopathy'), ('severe', 'Severe Diabetic Retinopathy'), ('proliferative', 'Proliferative Diabetic Retinopathy')], max_length=50)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
