# Generated by Django 5.2.6 on 2025-09-14 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('common_foods', models.TextField(help_text='Common traditional foods in this country')),
            ],
        ),
        migrations.AddField(
            model_name='dietaryrecommendation',
            name='evening_foods',
            field=models.TextField(default='Baked fish, Steamed vegetables, Quinoa', help_text='Foods to eat for dinner (7-9 PM)'),
        ),
        migrations.AddField(
            model_name='dietaryrecommendation',
            name='general_advice',
            field=models.TextField(default='Maintain balanced meals with controlled carbohydrates', help_text='General dietary advice'),
        ),
        migrations.AddField(
            model_name='dietaryrecommendation',
            name='hydration',
            field=models.TextField(default='Drink 8-10 glasses of water daily', help_text='Hydration recommendations'),
        ),
        migrations.AddField(
            model_name='dietaryrecommendation',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use as default for countries without specific recommendations'),
        ),
        migrations.AddField(
            model_name='dietaryrecommendation',
            name='midday_foods',
            field=models.TextField(default='Grilled chicken salad, Vegetable soup', help_text='Foods to eat for lunch (12-2 PM)'),
        ),
        migrations.AddField(
            model_name='dietaryrecommendation',
            name='morning_foods',
            field=models.TextField(default='Whole grain cereal, Eggs, Greek yogurt', help_text='Foods to eat for breakfast (7-9 AM)'),
        ),
        migrations.AddField(
            model_name='dietaryrecommendation',
            name='snack_foods',
            field=models.TextField(default='Apple slices, Almonds, Carrot sticks', help_text='Foods to eat for snacks (10-11 AM, 4-5 PM)'),
        ),
        migrations.AlterField(
            model_name='dietaryrecommendation',
            name='foods_to_avoid',
            field=models.TextField(default='Sugary foods, Processed snacks, White bread', help_text='Foods to avoid completely'),
        ),
        migrations.AddField(
            model_name='dietaryrecommendation',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.country'),
        ),
        migrations.AlterUniqueTogether(
            name='dietaryrecommendation',
            unique_together={('condition', 'country')},
        ),
        migrations.RemoveField(
            model_name='dietaryrecommendation',
            name='foods_to_eat',
        ),
        migrations.RemoveField(
            model_name='dietaryrecommendation',
            name='recommendation_text',
        ),
    ]
