# Generated by Django 5.2.6 on 2025-09-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_country_dietaryrecommendation_evening_foods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietaryrecommendation',
            name='hydration',
        ),
        migrations.AddField(
            model_name='dietaryrecommendation',
            name='eye_care_recommendations',
            field=models.TextField(default='Limit screen time, wear sunglasses outdoors, regular eye checkups', help_text='Eye care recommendations based on condition stage'),
        ),
    ]
