# Generated by Django 5.2.6 on 2025-09-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_remove_dietaryrecommendation_hydration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietaryrecommendation',
            options={'verbose_name': 'Dietary Recommendation', 'verbose_name_plural': 'Dietary Recommendations'},
        ),
        migrations.AddField(
            model_name='dietaryrecommendation',
            name='calories',
            field=models.CharField(blank=True, help_text='Recommended daily calories (e.g., 1800 kcal)', max_length=100),
        ),
        migrations.AddField(
            model_name='dietaryrecommendation',
            name='eye_exercises',
            field=models.TextField(default='Eye rolling, Palming, Focus shifting exercises.', help_text='Specific eye exercises for this condition'),
        ),
        migrations.AddField(
            model_name='retinopathytest',
            name='daily_calories',
            field=models.FloatField(blank=True, help_text='Recommended daily calories', null=True),
        ),
        migrations.AddField(
            model_name='retinopathytest',
            name='patient_weight',
            field=models.FloatField(blank=True, help_text='Patient weight in kg', null=True),
        ),
        migrations.AlterField(
            model_name='dietaryrecommendation',
            name='eye_care_recommendations',
            field=models.TextField(default='Limit screen time, wear sunglasses outdoors, regular eye checkups.', help_text='Eye care recommendations based on condition stage'),
        ),
        migrations.AlterField(
            model_name='dietaryrecommendation',
            name='general_advice',
            field=models.TextField(default='Maintain balanced meals with controlled carbohydrates.', help_text='General dietary advice'),
        ),
    ]
