# Generated by Django 5.2.6 on 2025-09-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_alter_dietaryrecommendation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietaryrecommendation',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='retinopathytest',
            name='daily_calories',
        ),
        migrations.RemoveField(
            model_name='retinopathytest',
            name='patient_weight',
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
